version: '3.1'

services:

  db:
    image: postgres
    container_name: db_task
    ports:
      - 5436:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 125436
      POSTGRES_DB: pgdb

  adminer:
    image: adminer
    container_name: adminer_db_task
    links:
      - db
    ports:
      - 8081:8080
